### ISSUE TITLE
Link to HTML Help Workshop Download is dead

### ISSUE THREAD

**Issue by mistrey** [burkhard154/makestudio#2]
The link to the Microsoft page doesn't work anymore. I managed to download and install Version 1.3 but cannot start MakeStudio anyway.

**Comment by pjrobin** [comment]
Hi, thanks for the report. I'll check that. In the meaning while, you can still use MakeStudio by closing the dialog with alt-F4

**Comment by mistrey** [comment]
Thanks for the helpful hint!

**Comment by pyscripter** [comment]
https://www.helpandmanual.com/downloads_mscomp.html contains a valid link.

Incidentally, this is a project is a hidden gem, that has not received well-deserved attention.  I am using it in making releases for [pyscripter](https://github.com/pyscripter/pyscripter).

**Comment by pjrobin** [comment]
Tested, should be ok now
